name = "Ssmp Modded"
author = "sosiski.lol"
version = "0.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "8291d3ef1ecf0d7130dc39449ef41d6a1f208188c5fa916be4d7668870e65f7e"

[versions]
fabric = "0.15.11"
minecraft = "1.19.2"
