name = "Ssmp Modded"
author = "sosiski.lol"
version = "0.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "95f473058518a5a002bdd5699ee81ea0a9eb97be8edcfc1996faadc1a845fe90"

[versions]
fabric = "0.15.11"
minecraft = "1.20.1"
