name = "Ssmp Modded"
author = "sosiski.lol"
version = "0.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "139006d8660248f3f54c720e82c59d355ec5414c72766bb6892b567473f4fe45"

[versions]
fabric = "0.15.11"
minecraft = "1.20.1"
