name = "Ssmp Modded"
author = "sosiski.lol"
version = "0.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "5a16e8d80cd3a3a8134d2f50122248638af67f96f5d8d9c3035a62cae3047bb7"

[versions]
fabric = "0.15.11"
minecraft = "1.20.1"
