name = "Ssmp Modded"
author = "sosiski.lol"
version = "0.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "3cfa5899b1e26bfe033cd33ec55279b75b508432b4c4bcd291772b56e42a5fc5"

[versions]
fabric = "0.15.11"
minecraft = "1.20.1"
