name = "Ssmp Modded"
author = "sosiski.lol"
version = "0.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "6c3004b7bf6fcd88c8e5e9c59af23fc68bbfe11a3c4a4c235d80e0850baa7845"

[versions]
fabric = "0.15.11"
minecraft = "1.20.1"
