name = "Ssmp Modded"
author = "sosiski.lol"
version = "0.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "28682efc87bc62d5c4dc404cc28d39a2beb5c37d8e85d88aa511bb446ec88fae"

[versions]
fabric = "0.15.11"
minecraft = "1.20.1"
