name = "Ssmp Modded"
author = "sosiski.lol"
version = "0.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "72d0f92f922f08970071f349153f894734284d4897950beeb88358e872065eaf"

[versions]
fabric = "0.15.11"
minecraft = "1.20.1"
