name = "Ssmp Modded"
author = "sosiski.lol"
version = "0.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "956af29b08540a900f49c25c73217f0b9e81feefcdd583456828724a793128ce"

[versions]
fabric = "0.15.11"
minecraft = "1.20.1"
