name = "Ssmp Modded"
author = "sosiski.lol"
version = "0.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "14513b7d549cb2737494035327089fdc3dcf0c8634ae31c450b79e5b635f7609"

[versions]
fabric = "0.15.11"
minecraft = "1.20.1"
