name = "Ssmp Modded"
author = "sosiski.lol"
version = "0.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "8571cdbd8f91910388edf401aa2ce78765e526a278420b0299cdc622e2dd4015"

[versions]
fabric = "0.15.11"
minecraft = "1.20.1"
