name = "Ssmp Modded"
author = "sosiski.lol"
version = "0.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "64981b6685d7f7ab96d69bd46badd382cf7cfb9a6861df4dade355af1f1cbd74"

[versions]
fabric = "0.15.11"
minecraft = "1.19.2"
