name = "Ssmp Modded"
author = "sosiski.lol"
version = "0.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "def3ee39c7b10a0d519031165a4c057386e8d3afe7260465596735364ab42872"

[versions]
fabric = "0.15.11"
minecraft = "1.20.1"
