name = "Ssmp Modded"
author = "sosiski.lol"
version = "0.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "64e590e48db842ef8abcaff531475198a8046ff8fd44047a0eb5210b5a78306c"

[versions]
fabric = "0.15.11"
minecraft = "1.20.1"
