name = "Ssmp Modded"
author = "sosiski.lol"
version = "0.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "fcebf54924710072a6930d60ed09ee29b4ec92f3d90b5280a4bb38c39be6e9af"

[versions]
fabric = "0.15.11"
minecraft = "1.19.2"
