name = "Ssmp Modded"
author = "sosiski.lol"
version = "0.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "9b052c86b8cb7b3a7098928a3b9c43e09e556d64f93f6131483e201dbaf4a835"

[versions]
fabric = "0.15.11"
minecraft = "1.20.1"
