name = "Ssmp Modded"
author = "sosiski.lol"
version = "0.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "4b937dffa263194138ba75f6a536d44a19b668bd5c1056f6b15118f1e635b0b2"

[versions]
fabric = "0.15.11"
minecraft = "1.20.1"
