name = "Ssmp Modded"
author = "sosiski.lol"
version = "0.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f6c1ed73e9a904d32f5a838d6db31c019676a8d66ac5b5d7ae7d8028906fbb8e"

[versions]
fabric = "0.15.11"
minecraft = "1.20.1"
