name = "Ssmp Modded"
author = "sosiski.lol"
version = "0.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e4e840b3723a7a938cb8549f3c0238f46f281f1daff4d6ac0bf5a6f700f7099b"

[versions]
fabric = "0.15.11"
minecraft = "1.20.1"
